# Generated by Django 3.1.3 on 2021-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='user_faces/'),
        ),
    ]
