# Generated by Django 3.1.3 on 2021-02-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_review_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='isparent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='parentreview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.review'),
        ),
    ]
