# Generated by Django 3.1.3 on 2021-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_videomodels_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_newsletter',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
