# Generated by Django 3.1.3 on 2021-02-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210214_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_newsletter',
            field=models.BooleanField(null=True),
        ),
    ]
